### PR TITLE
add_xsd_model wrapper

### PR DESCRIPTION
**Pull request by expede**

### CODE REVIEW

**Comment by expede** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2xqG4VA5&#x2F;15-wrap-add-xsd-model"> Wrap add_xsd_model</a>

**Comment by expede** [comment]
GH Integration test

**Comment by icidasset** [comment]
Is this ready to merge?

**Comment by expede** [comment]
Wow, I forgot about this branch completely 😛 Could use some `spec`s and `doc`s... but sure, may as well merge for now

**Comment by icidasset** [comment]
😄 Cool. I'll merge this, together with the other one (after you checked it), and then I'll work from there.

**Pull request merged**
